### ISSUE TITLE
你好，能不能不用emoji做命名？

### ISSUE THREAD

**Issue by AmenLi** [jinyu121/SurgeRule#2]

**Comment by jinyu121** [comment]
我知道这样确实不好编辑……但是好看啊～

我正在考虑加入一些替换的东西。

你可以使用Workflow来进行更新。

**Comment by Ohuisang** [comment]
emoji surge里面不能用。。。

**Comment by jinyu121** [comment]
Surge2里面可用Emoj，Mac版不清楚（求赞助一台Mac进行测试）
为适配Surge3,已去掉所有Emoj
