### ISSUE TITLE
能否悬浮显示大概的代理内容。

### ISSUE THREAD

**Issue by zanderzhng** [jinyu121/SurgeRule#3]
目前的一些配置的描述还是会让人误解。
例如两个激进规则的选项的里边到底是什么内容，有没有一个办法让它们大概的显示出来？
不需要完全显示，用户能看个大概就可以了。

**Comment by jinyu121** [comment]
不是特别想做这个。

首先，我不想什么都写得太明白了。

其次，代码太长不利于维护。lhie1可能有自动化工具，但是我没有。

这个项目仅仅是为了 __我__ 能用着比较顺手而已。

PS： 两个提示已加入。

**Comment by jinyu121** [comment]
我更改了代码，现在你可以很轻松地加入悬浮提示了。
